version: "3.8"
services:

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default: